// Command catalog inspects the redfish_exporter metric catalog.
//
//	catalog list [--format text|markdown|csv] [--out <dir>]
//
// `list` renders every catalog entry known to internal/catalog.
package main

import (
	"bytes"
	"encoding/csv"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/LambdaLabs/redfish_exporter/internal/catalog"
)

func main() {
	if len(os.Args) < 2 {
		printUsage(os.Stderr)
		os.Exit(2)
	}
	switch os.Args[1] {
	case "list":
		if err := runList(os.Args[2:]); err != nil {
			fmt.Fprintln(os.Stderr, "catalog list:", err)
			os.Exit(1)
		}
	case "-h", "--help", "help":
		printUsage(os.Stdout)
	default:
		fmt.Fprintf(os.Stderr, "unknown subcommand %q\n", os.Args[1])
		printUsage(os.Stderr)
		os.Exit(2)
	}
}

func printUsage(w io.Writer) {
	fmt.Fprint(w, `catalog — inspect the redfish_exporter metric catalog.

Usage:
  catalog list [--format text|markdown|csv] [--out <dir>]

Subcommands:
  list   Print every catalog entry known to the exporter.
`)
}

// -- list ---------------------------------------------------------------------

func runList(args []string) error {
	fs := flag.NewFlagSet("list", flag.ExitOnError)
	format := fs.String("format", "text", "output format: text, markdown, csv")
	outDir := fs.String("out", "", "output directory (markdown only): writes README.md + one file per module")
	if err := fs.Parse(args); err != nil {
		return err
	}
	modules := catalog.All()
	switch *format {
	case "text":
		if *outDir != "" {
			return errors.New("--out is only supported with --format markdown")
		}
		return writeText(os.Stdout, modules)
	case "markdown", "md":
		if *outDir != "" {
			return writeMarkdownDir(*outDir, modules)
		}
		return writeMarkdown(os.Stdout, modules)
	case "csv":
		if *outDir != "" {
			return errors.New("--out is only supported with --format markdown")
		}
		return writeCSV(os.Stdout, modules)
	default:
		return fmt.Errorf("unknown --format %q (want text, markdown, or csv)", *format)
	}
}

func writeText(w io.Writer, modules []catalog.Module) error {
	for i, m := range modules {
		if i > 0 {
			fmt.Fprintln(w)
		}
		printModule(w, m)
	}
	return nil
}

func printModule(w io.Writer, m catalog.Module) {
	fmt.Fprintf(w, "== %s (%d metrics)\n", m.Name, len(m.Entries))
	if len(m.Entries) == 0 {
		if m.Description != "" {
			fmt.Fprintf(w, "  %s\n", m.Description)
		} else {
			fmt.Fprintln(w, "  (no entries — TODO)")
		}
		return
	}
	for _, e := range m.Entries {
		fmt.Fprintf(w, "  %s\n", e.Name)
		fmt.Fprintf(w, "    help:  %s\n", e.Help)
		fmt.Fprintf(w, "    type:  %s / %s\n", e.MetricType, csvValueType(e))
		if e.Enum != nil {
			var pairs []string
			for _, v := range e.Enum.Values {
				pairs = append(pairs, fmt.Sprintf("%d=%s", v.Code, v.Label))
			}
			fmt.Fprintf(w, "    enum:  %s\n", strings.Join(pairs, ", "))
		}
		fmt.Fprintf(w, "    value: %s :: %s\n", e.Value.Path, e.Value.Field)
		for _, l := range e.Labels {
			path := l.Path
			if path == "" {
				path = "(same as value)"
			}
			field := l.Field
			if field == "" {
				field = "(constant)"
			}
			fmt.Fprintf(w, "    label %s = %s :: %s  — %s\n", l.Name, path, field, l.Description)
		}
	}
}

func writeMarkdown(w io.Writer, modules []catalog.Module) error {
	fmt.Fprintln(w, "# redfish_exporter metric catalog")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Generated by `catalog list --format markdown`. Every metric emitted by")
	fmt.Fprintln(w, "the exporter, annotated with its Redfish source endpoint and the field")
	fmt.Fprintln(w, "each label is read from.")
	fmt.Fprintln(w)

	// Table of contents.
	fmt.Fprintln(w, "## Modules")
	fmt.Fprintln(w)
	for _, m := range modules {
		fmt.Fprintf(w, "- [%s](#module-%s) — %d metrics\n", m.Name, m.Name, len(m.Entries))
	}
	fmt.Fprintln(w)

	// Global overview: one flat table covering every module. Meant for
	// grep/scan; per-module H2 sections below carry the per-label details.
	total := 0
	for _, m := range modules {
		total += len(m.Entries)
	}
	fmt.Fprintf(w, "## Summary\n\nAll %d metrics across %d modules.\n\n",
		total, len(modules))
	fmt.Fprintln(w, "| Module | Metric | Metric Type | Value Type | Endpoint | Labels | Value | Description |")
	fmt.Fprintln(w, "|---|---|---|---|---|---|---|---|")
	for _, m := range modules {
		for _, e := range m.Entries {
			var names []string
			for _, l := range e.Labels {
				names = append(names, l.Name)
			}
			labels := strings.Join(names, ", ")
			if labels == "" {
				labels = "*(none)*"
			}
			fmt.Fprintf(w, "| %s | `%s` | %s | %s | `%s` | %s | `%s` | %s |\n",
				mdEscape(m.Name),
				mdEscape(e.Name),
				mdEscape(e.MetricType.String()),
				mdEscape(mdValueType(e)),
				mdEscape(e.Value.Path),
				mdEscape(labels),
				mdEscape(e.Value.Field),
				mdEscape(e.Help))
		}
	}
	fmt.Fprintln(w)

	for _, m := range modules {
		fmt.Fprintf(w, "## Module: %s\n", m.Name)
		fmt.Fprintln(w)
		if len(m.Entries) == 0 {
			if m.Description != "" {
				fmt.Fprintf(w, "%s\n\n", m.Description)
			} else {
				fmt.Fprintln(w, "*No entries — module has not been catalogued yet.*")
				fmt.Fprintln(w)
			}
			continue
		}
		for _, e := range m.Entries {
			writeMarkdownEntry(w, e)
		}
	}
	return nil
}

// writeCSV emits the catalog as a flat CSV table:
// module, metric, description, metric_type, labels, value_type, value,
// possible_values, endpoint, original_endpoint.
// Labels within a row are joined by "; " so a single CSV cell carries the
// list; standard CSV quoting handles any embedded commas or quotes.
// possible_values is populated (e.g. "1=OK, 2=Warning, 3=Critical") only when
// value_type is "int_enum"; otherwise it is empty.
// original_endpoint is the underlying Redfish resource path for TelemetryService
// entries; empty for all other collectors.
func writeCSV(w io.Writer, modules []catalog.Module) error {
	cw := csv.NewWriter(w)
	if err := cw.Write([]string{"module", "metric", "description", "metric_type", "labels", "label_sources", "value_type", "value", "possible_values", "endpoint", "original_endpoint"}); err != nil {
		return err
	}
	for _, m := range modules {
		for _, e := range m.Entries {
			var names, sources []string
			for _, l := range e.Labels {
				names = append(names, l.Name)
				var src string
				switch {
				case l.Constant != "":
					src = l.Name + "=\"" + l.Constant + "\""
				case l.Field != "":
					src = l.Name + "=." + l.Field
				default:
					src = l.Name + "=(config)"
				}
				sources = append(sources, src)
			}
			row := []string{
				m.Name,
				e.Name,
				e.Help,
				e.MetricType.String(),
				strings.Join(names, "; "),
				strings.Join(sources, "; "),
				csvValueType(e),
				e.Value.Field,
				csvEnumValues(e),
				e.Value.Path,
				e.Value.OriginalPath,
			}
			if err := cw.Write(row); err != nil {
				return err
			}
		}
	}
	cw.Flush()
	return cw.Error()
}

func csvValueType(e catalog.Entry) string {
	if e.ValueType == catalog.ValueIntEnum && e.Enum != nil {
		return "int_enum(" + e.Enum.Name + ")"
	}
	return e.ValueType.String()
}

func csvEnumValues(e catalog.Entry) string {
	if e.Enum == nil {
		return ""
	}
	parts := make([]string, 0, len(e.Enum.Values))
	for _, v := range e.Enum.Values {
		parts = append(parts, fmt.Sprintf("%d=%s", v.Code, v.Label))
	}
	return strings.Join(parts, ", ")
}

// writeMarkdownDir splits the markdown output across a directory: one
// README.md with the global overview + summary table, plus one file per
// module carrying the per-metric detail sections.
func writeMarkdownDir(dir string, modules []catalog.Module) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating %s: %w", dir, err)
	}

	// README.md — overview + links to per-module files + global summary.
	var readme bytes.Buffer
	writeMarkdownOverview(&readme, modules)
	readmePath := filepath.Join(dir, "README.md")
	if err := os.WriteFile(readmePath, readme.Bytes(), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", readmePath, err)
	}

	// One file per module.
	for _, m := range modules {
		var buf bytes.Buffer
		writeMarkdownModuleFile(&buf, m)
		modPath := filepath.Join(dir, m.Name+".md")
		if err := os.WriteFile(modPath, buf.Bytes(), 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", modPath, err)
		}
	}

	// Progress hint on stderr so the caller sees where things landed.
	fmt.Fprintf(os.Stderr, "wrote %s and %d per-module files under %s\n",
		"README.md", len(modules), dir)
	return nil
}

// writeMarkdownOverview writes the top-level catalog overview: title, module
// list with links, and a global Summary table listing every metric.
func writeMarkdownOverview(w io.Writer, modules []catalog.Module) {
	fmt.Fprintln(w, "# redfish_exporter metric catalog")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Generated by `catalog list --format markdown --out <dir>`. Every metric")
	fmt.Fprintln(w, "emitted by the exporter, annotated with its Redfish source endpoint and")
	fmt.Fprintln(w, "the field each label is read from.")
	fmt.Fprintln(w)

	fmt.Fprintln(w, "## Modules")
	fmt.Fprintln(w)
	for _, m := range modules {
		fmt.Fprintf(w, "- [%s](%s.md) — %d metrics\n", m.Name, m.Name, len(m.Entries))
	}
	fmt.Fprintln(w)

	total := 0
	for _, m := range modules {
		total += len(m.Entries)
	}
	fmt.Fprintf(w, "## Summary\n\nAll %d metrics across %d modules.\n\n",
		total, len(modules))
	fmt.Fprintln(w, "| Module | Metric | Metric Type | Value Type | Endpoint | Labels | Value | Description |")
	fmt.Fprintln(w, "|---|---|---|---|---|---|---|---|")
	for _, m := range modules {
		for _, e := range m.Entries {
			var names []string
			for _, l := range e.Labels {
				names = append(names, l.Name)
			}
			labels := strings.Join(names, ", ")
			if labels == "" {
				labels = "*(none)*"
			}
			fmt.Fprintf(w, "| [%s](%s.md) | `%s` | %s | %s | `%s` | %s | `%s` | %s |\n",
				mdEscape(m.Name),
				mdEscape(m.Name),
				mdEscape(e.Name),
				mdEscape(e.MetricType.String()),
				mdEscape(mdValueType(e)),
				mdEscape(e.Value.Path),
				mdEscape(labels),
				mdEscape(e.Value.Field),
				mdEscape(e.Help))
		}
	}
	fmt.Fprintln(w)
}

// writeMarkdownModuleFile writes the per-metric details for a single module.
func writeMarkdownModuleFile(w io.Writer, m catalog.Module) {
	fmt.Fprintf(w, "# Module: %s\n\n", m.Name)
	fmt.Fprintf(w, "**%d metrics.**\n\n", len(m.Entries))
	fmt.Fprintln(w, "Back to [overview](README.md).")
	fmt.Fprintln(w)

	if len(m.Entries) == 0 {
		if m.Description != "" {
			fmt.Fprintf(w, "%s\n\n", m.Description)
		} else {
			fmt.Fprintln(w, "*No entries — module has not been catalogued yet.*")
			fmt.Fprintln(w)
		}
		return
	}

	for _, e := range m.Entries {
		writeMarkdownEntry(w, e)
	}
}

// writeMarkdownEntry writes the H3 detail block for a single metric — used
// by both the single-file and per-module writers.
func writeMarkdownEntry(w io.Writer, e catalog.Entry) {
	fmt.Fprintf(w, "### `%s`\n\n", e.Name)
	fmt.Fprintf(w, "%s\n\n", e.Help)
	fmt.Fprintf(w, "**Type:** %s — **Value:** %s\n\n",
		e.MetricType.String(), mdValueType(e))
	if e.Enum != nil {
		fmt.Fprintf(w, "**Enum `%s`:**\n\n", e.Enum.Name)
		fmt.Fprintln(w, "| Code | Label |")
		fmt.Fprintln(w, "|---|---|")
		for _, v := range e.Enum.Values {
			fmt.Fprintf(w, "| %d | %s |\n", v.Code, v.Label)
		}
		fmt.Fprintln(w)
	}
	fmt.Fprintf(w, "**Value source:** `%s` → `%s`\n\n",
		mdEscape(e.Value.Path), mdEscape(e.Value.Field))
	if e.Value.OriginalPath != "" {
		fmt.Fprintf(w, "**Original source:** `%s`\n\n", mdEscape(e.Value.OriginalPath))
	}
	if len(e.Labels) == 0 {
		fmt.Fprintln(w, "**Labels:** none.")
		fmt.Fprintln(w)
		return
	}
	fmt.Fprintln(w, "**Labels:**")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "| Name | Endpoint | Field | Description |")
	fmt.Fprintln(w, "|---|---|---|---|")
	for _, l := range e.Labels {
		endpoint := l.Path
		if endpoint == "" {
			endpoint = "*(same as value)*"
		} else {
			endpoint = "`" + mdEscape(endpoint) + "`"
		}
		field := l.Field
		if field == "" {
			field = "*(constant)*"
		} else {
			field = "`" + mdEscape(field) + "`"
		}
		fmt.Fprintf(w, "| `%s` | %s | %s | %s |\n",
			mdEscape(l.Name), endpoint, field, mdEscape(l.Description))
	}
	fmt.Fprintln(w)
}

// mdValueType returns the value type string for markdown cells. For int_enum
// entries it includes the enum name for quick reference.
func mdValueType(e catalog.Entry) string {
	if e.ValueType == catalog.ValueIntEnum && e.Enum != nil {
		return "int\\_enum (" + e.Enum.Name + ")"
	}
	return e.ValueType.String()
}

// mdEscape escapes pipe characters and backticks that would confuse the
// enclosing table cell or inline-code span. Callers wrap the result in
// backticks or a plain cell as appropriate.
func mdEscape(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	// Backticks inside cells are rendered as literal characters by common
	// markdown parsers, but keep escaping conservative.
	return s
}
